version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - microservices-network

  kafka:
    image: bitnami/kafka
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - microservices-network

  payment-service:
    build:
      context: .
      dockerfile: ./payment/Dockerfile
    container_name: payment-service
    env_file:
      - .env
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "3001:3001"
    networks:
      - microservices-network

  shipping-service:
    build:
      context: .
      dockerfile: ./shipping/Dockerfile
    container_name: shipping-service
    env_file:
      - .env
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "3002:3002"
    networks:
      - microservices-network

  notifications-service:
    build:
      context: .
      dockerfile: ./notifications/Dockerfile
    container_name: notifications-service
    env_file:
      - .env
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
    ports:
      - "3003:3003"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge