version: '3.5'
# --- docker-compose-metric.yml---
services:
# --- Monitoring Stack ---  
  prometheus:
    image: prom/prometheus:v2.21.0
    container_name: prometheus
    volumes:
      - ./etc/prometheus/:/etc/prometheus/  # Make sure you have a valid Prometheus config file in this directory.
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    restart: always
    depends_on:
      - alertmanager
    networks:
      - metrics-network

  grafana:
    image: grafana/grafana:6.5.0
    container_name: grafana
    ports:
      - "4000:3000"
    networks:
      - metrics-network
    restart: always
  alertmanager:
    image: prom/alertmanager:v0.22.2
    container_name: alertmanager
    volumes:
      - ./etc/alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - "9093:9093"
    networks:
      - metrics-network
    restart: always
  
networks:
  metrics-network:
    driver: bridge
    external: 
      name: shared-network