version: '3.8'

services:
  kafka:
    image: bitnami/kafka
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
  
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  payment-service:
    build: ./payment
    container_name: payment-service
    depends_on:
      - kafka
    ports:
      - "3001:3001"

  shipping-service:
    build: ./shipping
    container_name: shipping-service
    depends_on:
      - kafka
    ports:
      - "3002:3002"
 

