# --- APIproject/etc/prometheus/prometheus.yml---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'microservices'
    static_configs:
      - targets:
          - 'shipping-service:3002'
          - 'payment-service:3001'
          - 'notifications-service:3003'